### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gkapkowski** [marcinkaszynski/pytz-js#2]
For data (taken from this.toDate = function (date_dict, is_dst) ):

date_dict: Object
  date: 21
  hours: "3"
  minutes: "20"
  month: 9
  year: 2011

is_dst:
  undefined

I think that shifting and checking every millisecond is not the best idea, it fails around 140 line.

**Comment by marcinkaszynski** [comment]
Fixed.  The problem was that you did not specify seconds and the library would fail the wrong way on that.
It will now throw an exception in that case.

Thanks for reporting!
